config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "tours#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"

  # Defines the routes for the posts resource
  resources :tours, only: [:index, :show, :new, :create] do
    resources :bookings, only: [:new, :create, :show] do
      resources :reviews, only: [:new, :create]
        member do
          patch :accept
          patch :reject
          patch :cancel
          patch :complete
          patch :no_show
          patch :refund
        end
    end
  end

  # not needed?
  get "users/:id" => "users#show", as: :user

  resources :users, only: [:show] do
    resources :reviews, only: [:index, :destroy]
  end

  get "bookings/:id/edit" => "bookings#edit", as: :booking_edit
  patch "bookings/:id" => "bookings#update", as: :booking
  delete "bookings/:id" => "bookings#destroy", as: :booking_destroy


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  LANGUAGES = ["English", "French", "Spanish", "German", "Italian", "Japanese", "Korean", "Mandarin", "Portuguese",
               "Russian", "Simplified Chinese", "Traditional Chinese", "Vietnamese"]

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :bookings, dependent: :destroy
  has_many :tours, through: :bookings
  has_many :reviews, through: :bookings
  has_one_attached :photo
  has_many :tours, dependent: :destroy
  validates :email, presence: true
  validates :encrypted_password, presence: true
  validates :age, presence: true, numericality: { only_integer: true }
  validates :guide, inclusion: { in: [true, false] }
  validates :language, presence: true
  validates :first_name, presence: true
  validates :last_name, presence: true

  def guide_average_rating
    return unless guide

    all_ratings = Review.joins(booking: :tour).where(tours: { user_id: id }).pluck(:guide_rating)
    @guide_average_rating = all_ratings.sum.to_f / all_ratings.count
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show]

  def show
    @bookings = Booking.joins(:tour).where(tours: { user_id: @user.id }).order(updated_at: :desc).to_a
    Rails.logger.debug "Bookings loaded for guide: #{@bookings.pluck(:id, :status)}"
    @tours = Tour.where(user_id: @user.id).order(updated_at: :desc).to_a

    @reviews_guide = Review.joins(booking: :tour).where(tours: { user_id: @user.id })
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :age, :language, :guide, :about_me, :photo)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/views/users/_guide_booked_tours.html.erb
<% if current_user.id == @user.id %>
  <% if @bookings.any? %>
    <% @bookings.each do |booking| %>
      <% if booking.tour.user_id == @user.id && booking.date >= Date.today %>
        <div class="col-6">
          <div class="card-trip m-3 position-relative">
            <%= link_to tour_path(booking.tour) do %>
              <%= image_tag(booking.tour.photo) %>
            <% end %>
            <%#= cl_image_tag(booking.tour.photo.key, class: "card-trip-user-image") %>
            <% if booking.status == "Pending" %>
              <div class="d-flex justify-content-center align-items-center text-center" >
                <div class="overlay p-3 d-flex justify-content-center align-items-center text-center" >
                  <h5><%= link_to "Accept", accept_tour_booking_path(booking.tour, booking), data: { turbo_method: :patch } %></h5>
                </div>
                <div class="overlay-reject p-3 d-flex justify-content-center align-items-center text-center" >
                  <h5><%= link_to "Reject", reject_tour_booking_path(booking.tour, booking), data: { turbo_method: :patch } %></h5>
                </div>
                <div class="overlay-refund p-3 d-flex justify-content-center align-items-center text-center" >
                  <h5><%= link_to "Refund", refund_tour_booking_path(booking.tour, booking), data: { turbo_method: :patch } %></h5>
                </div>
              </div>
            <% else %>
              <div class="overlay p-3 d-flex justify-content-center align-items-center text-center" >
                <h5><%= booking.status %></h5>
              </div>
            <% end %>
            <div class="card-trip-infos d-flex justify-content-between">
              <div class="card-trip-description">
                <div>
                  <p><%= link_to booking.tour.name, tour_path(booking.tour), class:"card-link" %></p>
                  <p>Client: <%= link_to booking.user.first_name, user_path(booking.user), class:"card-link" %></p>
                  <p>Date: <%= booking.date %></p>
                </div>
              </div>
              <% if booking.status == "Confirmed" && Date.today >= booking.date %>
                <div class="d-flex justify-content-center align-items-center mb-1" >
                  <%= link_to "No Show", no_show_tour_booking_path(booking.tour, booking), data: { turbo_method: :patch }, class: "btn btn-secondary" %>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  <% else %>
    <h2>You have no bookings pending approval.</h2>
  <% end %>
<% end %>

app/views/users/_guide_past_tours.html.erb
<% if current_user.id == @user.id %>
  <% if @bookings.any? %>
    <% @bookings.each do |booking| %>
      <% if booking.tour.user_id == @user.id && booking.date < Date.today %>
        <% if booking.status == "Pending" || booking.status == "Confirmed" %>
          <% booking.status = "Completed" %>
        <% end %>
        <div class="col-6">
          <div class="card-trip m-3 position-relative">
            <%= link_to tour_path(booking.tour) do %>
              <%= image_tag(booking.tour.photo) %>
            <% end %>
            <%#= cl_image_tag(booking.tour.photo.key, class: "card-trip-user-image") %>
            <% if booking.status == "Pending" %>
              <div class="d-flex justify-content-center align-items-center text-center" >
                <div class="overlay p-3 d-flex justify-content-center align-items-center text-center" >
                  <h5><%= link_to "Accept", accept_tour_booking_path(booking.tour, booking), data: { turbo_method: :patch } %></h5>
                </div>
                <div class="overlay-reject p-3 d-flex justify-content-center align-items-center text-center" >
                  <h5><%= link_to "Reject", reject_tour_booking_path(booking.tour, booking), data: { turbo_method: :patch } %></h5>
                </div>
                <div class="overlay-refund p-3 d-flex justify-content-center align-items-center text-center" >
                  <h5><%= link_to "Refund", refund_tour_booking_path(booking.tour, booking), data: { turbo_method: :patch } %></h5>
                </div>
              </div>
            <% else %>
              <div class="overlay p-3 d-flex justify-content-center align-items-center text-center" >
                <h5><%= booking.status %></h5>
              </div>
            <% end %>
            <div class="card-trip-infos d-flex justify-content-between">
              <div class="card-trip-description">
                <div>
                  <p><%= link_to booking.tour.name, tour_path(booking.tour), class:"card-link" %></p>
                  <p>Client: <%= link_to booking.user.first_name, user_path(booking.user), class:"card-link" %></p>
                  <p>Date: <%= booking.date %></p>
                </div>
              </div>
              <% if booking.status == "Confirmed" && Date.today >= booking.date %>
                <div class="d-flex justify-content-center align-items-center mb-1" >
                  <%= link_to "Declare No-show", no_show_tour_booking_path(booking.tour, booking), data: { turbo_method: :patch }, class: "btn btn-secondary" %>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  <% else %>
    <h2>You have no past bookings yet.</h2>
  <% end %>
<% end %>

app/views/users/_leftover_to_copy_paste.html.erb
              <div>
                <% if booking.status == "Pending" %>
                  <div class=" p-2 d-flex justify-content-center align-items-center text-center" style="background-color: #D5EEFF; border-radius: 15px">
                    <p><%= booking.status %></p>
                  </div>
                <% elsif booking.status == "Confirmed" %>
                  <div class=" p-2 d-flex justify-content-center align-items-center text-center" style="background-color:rgb(117, 255, 122); border-radius: 15px">
                    <p><%= booking.status %></p>
                  </div>
                <% elsif booking.status == "Rejected" %>
                  <div class=" p-2 d-flex justify-content-center align-items-center text-center" style="background-color:rgb(255, 117, 117); border-radius: 15px">
                    <p><%= booking.status %></p>
                  </div>~
                <% else %>
                  <div class=" p-2 d-flex justify-content-center align-items-center text-center" style="background-color: #D5EEFF; border-radius: 15px">
                    <p><%= booking.status %></p>
                  </div>
                <% end %>
              </div>
            </div>
            <% if booking.status != "Cancelled"  %>
              <%= link_to "Cancel", cancel_tour_booking_path(booking.tour, booking), data: { turbo_method: :patch } %>
            <% end %>
          </div>



<p><%= link_to "Accept", accept_tour_booking_path(booking.tour, booking), data: { turbo_method: :patch } %></p>
<p><%= link_to "Reject", reject_tour_booking_path(booking.tour, booking), data: { turbo_method: :patch } %></p>
<p><%= link_to "Refund", refund_tour_booking_path(booking.tour, booking), data: { turbo_method: :patch } %></p>

app/views/users/_reviews.html.erb
<h2>Reviews (<%= @user.guide_average_rating.round(1) %>)</h2>
<hr>

<% if @reviews_guide.present? %>
  <div class="py-3">
      <% @reviews_guide.each do |review| %>
          <p><strong><%= review.booking.user.first_name %> said about <%= review.booking.tour.name %></strong></p>

          <%= render "shared/review_content", review: review %>
          <%= render "shared/review_stars", review: review %>

          <hr>
        <% end %>
  </div>
  <% else %>
    <p class="fw-light"> <%= @user.first_name %> has no reviews yet.</p>
  <% end %>

app/views/users/_tourist_bought_bookings.html.erb
<% if current_user.id == @user.id %>
  <% if @user.bookings.any? %>
    <% @user.bookings.each do |booking| %>
      <% if booking.date >= Date.today %>
        <div class="col-6">
          <div class="card-trip m-3 position-relative">
            <%= link_to tour_path(booking.tour) do %>
              <%= image_tag(booking.tour.photo) %>
            <% end %>
            <%#= cl_image_tag(booking.tour.photo.key, class: "card-trip-user-image") %>
            <div class="overlay p-3 d-flex justify-content-center align-items-center text-center" >
              <h5><%= booking.status %></h5>
            </div>
            <div class="card-trip-infos">
              <div class="card-trip-description">
                <div>
                  <p><%= link_to booking.tour.name, tour_path(booking.tour), class:"card-link" %></p>
                  <p>Guide: <%= link_to booking.tour.user.first_name, user_path(booking.tour.user), class:"card-link" %></p>
                  <p>Date: <%= booking.date %></p>
                </div>
                <div>
                </div>
              </div>
            </div>
          </div>
        </div>
      <% end %>

    <% end %>
  </div>
  <% else %>
    <h4><%= link_to "Book a tour", root_path, class: "btn btn-primary mt-3 mb-3"%></h4>
  <% end %>
<% else %>
  <h4>You are not authorized to see this user's bookings</h4>
  <%# Eventually add in here the reviews that the client has made in the past %>
<% end %>

app/views/users/_tourist_past_bookings.html.erb
<% if current_user.id == @user.id %>
  <% if @user.bookings.any? %>
    <% @user.bookings.each do |booking| %>
      <% if booking.status == "Pending" || booking.status == "Confirmed" %>
        <% booking.status = "Completed" %>
      <% end %>
      <% if booking.date < Date.today %>
        <div class="col-6">
          <div class="card-trip m-3 position-relative">
            <%= link_to tour_path(booking.tour) do %>
              <%= image_tag(booking.tour.photo) %>
            <% end %>
            <%#= cl_image_tag(booking.tour.photo.key, class: "card-trip-user-image") %>
            <div class="overlay p-3 d-flex justify-content-center align-items-center text-center" >
              <h5><%= booking.status %></h5>
            </div>
            <div class="card-trip-infos d-flex justify-content-between">
              <div class="card-trip-description">
                <div>
                  <p><%= link_to booking.tour.name, tour_path(booking.tour), class:"card-link" %></p>
                  <p>Guide: <%= link_to booking.tour.user.first_name, user_path(booking.tour.user), class:"card-link" %></p>
                  <p>Date: <%= booking.date %></p>
                </div>
              </div>
              <% if booking.status == "Completed" && booking.review.nil? %>
                <div class="d-flex justify-content-center align-items-center mb-1" >
                  <%= link_to "Review", new_tour_booking_review_path(booking.tour.id, booking.id), class: "btn btn-secondary" %>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
  <% else %>
    <h2>You have no bookings yet!</h2>
    <h3>Get ready to explore the world. <%= link_to "Book a tour", root_path, style: "text-decoration: none"%></h3>
  <% end %>
<% else %>
  <p>You are not authorized to view this user's bookings</p>
<% end %>

app/views/users/_tours_provided.html.erb
<% @tours.each do |tour| %>
  <div class="col-6">
    <div class="card-trip m-3">
      <%= link_to tour_path(tour) do %>
        <%= image_tag(tour.photo) %>
      <% end %>
      <%#= cl_image_tag(tour.photo.key) %>
      <div class="card-trip-infos">
        <div class="card-trip-description">
          <div>
            <p><%= link_to tour.name, tour_path(tour), class:"card-link" %></p>
            <p><%= tour.description %></p>
          </div>
          <h2 class="card-trip-pricing"><%= tour.price %>€</h2>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/users/_user_bookings.html.erb
<% if current_user.id == @user.id %>
      <% if @user.bookings.any? %>
        <% @user.bookings.each do |booking| %>
          <p>Tour: <%= booking.tour.name %></p>
          <p>Date: <%= booking.date %></p>
          <p>Nº of people: <%= booking.pax %></p>
          <p><%= link_to "Edit Booking", booking_edit_path(booking) %></p>
          <p><%= link_to "Cancel Booking", booking_destroy_path(booking), data: { turbo_method: :delete, turbo_confirm: "Are you sure?"} %></p>
        <% end %>
      <% else %>
        <p>you have no bookings yet!</p>
        <%= link_to "Book a tour", root_path%>
      <% end %>
    <% else %>
      <p>you are not authorized to view this user's bookings</p>
    <% end %>

app/views/users/edit.html.erb
<div class="container"></div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <%# LEFT COLUMN (Profile - 4 columns) %>
    <div class="col-4 p-4" id="profile">
      <div class="sticky-top">
        <div class="p-4 d-flex flex-column align-items-center position-relative" id="profile-box">
          <% if current_user && current_user.id == @user.id %>
            <h1>
              <%= link_to content_tag(:i, "", class: "fa-solid fa-pencil position-absolute top-0 end-0 mt-3 me-3"), edit_user_registration_path(@user) %>
            </h1>
          <% end %>
          <div class="mb-4">
            <% if @user.photo.key? %>
              <%= cl_image_tag @user.photo.key, height: 300, width: 300, crop: :fill, gravity: :face, class: "avatar-user-show" %>
            <% else %>
              <%= image_tag "https://plus.unsplash.com/premium_photo-1661764174171-c29f85bd8a37?q=80&w=2071&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D", height: 300, width: 300, class: "avatar-user-show" %>
            <% end %>
          </div>
          <div class="d-flex flex-column align-items-center mb-2">
            <h2><%= @user.first_name %> <%= @user.last_name %></h2>
            <% if @user.guide %>
              <h3>Tour Guide</h3>
            <% end %>
          </div>
          <div class="d-flex flex-column align-items-center text-center" id="profile-info">
            <div class="mb-3 mt-2">
              <h4>Speaks:</h4>
              <h6><%= @user.language %></h6>
            </div>
            <div class="mb-3">
              <h4>About me:</h4>
              <h6><%= @user.about_me %></h6>
            </div>
          </div>
          <% if current_user && current_user.id == @user.id %>
            <div class="p-2 d-flex flex-row align-items-center justify-content-between" id="buttons">
              <%= link_to "My Reviews", user_reviews_path(@user), class: "btn btn-secondary me-3" %>
              <%= link_to "Delete Profile", user_registration_path(@user), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "btn btn-delete" %>
            </div>
          <% end %>
        </div>
      </div>
    </div> <%# END col-4 Profile %>

    <%# RIGHT COLUMN (8 columns for Booking + Management) %>
    <div class="col-8 p-4">
      <%# BOOKING SECTION %>
      <% if !user_signed_in? || (@user.guide && @user.id != current_user.id) %>
        <div class="row">
          <div class="col-12">
            <div>
              <div class="mb-2">
                <h2>Tours Provided</h2>
              </div>
              <hr>
              <div class="row d-flex flex-wrap justify-content-start">
                <%= render "tours_provided" %>
              </div>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-12">
            <div>
              <%# <div class="mb-2 mt-2">
                <h2>Reviews</h2>
              </div> %>
              <%# <hr> %>
              <div class="row d-flex flex-wrap justify-content-start mt-2">
                <%= render "reviews" %>
              </div>
            </div>
          </div>
        </div>
      <% else %>
        <%# START OF UPCOMING TOURS %>
        <div class="row">
          <div class="col-12">
            <% if @user != current_user && !@user.guide %>
              <div>
                <div class="mb-2">
                  <h2>Reviews</h2>
                  <hr>
                  <div class="mb-2 mt-2">
                    <h4>What I think of these tours</h4>
                  </div>
                  <div class="row d-flex flex-wrap justify-content-start">
                    <%# ORSI RENDER USER REVIEWS ON THIS LINE %>
                  </div>
                </div>
              </div>
            </div>
            <% else %>
            <div>
              <div class="mb-2">
                <h2>Requested Tours</h2>
                <hr>
                <div class="mb-2 mt-2">
                  <h4>Get ready to explore the world</h4>
                </div>
              </div>
              <div class="row d-flex flex-wrap justify-content-start">
                <%= render "tourist_bought_bookings" %>
              </div>
            </div>
          </div>
          <% if @user.bookings.any? { |booking| booking.date < Date.today } %>
            <div class="col-12" id="to-review">
              <div>
                <div class="mb-2 mt-2">
                  <h4>Don't forget to leave a review</h4>
                </div>
                <div class="row d-flex flex-wrap justify-content-start">
                  <%= render "tourist_past_bookings" %>
                </div>
            <% end %>
            <% end %>



        <%# END OF UPCOMING TOURS %>

        <%# START OF BOOKING MANAGEMENT %>
        <% if current_user.id == @user.id && @user.guide %>
        <div class="row">
          <div class="col-12">
            <div>
              <div class="d-flex flex-row align-items-center justify-content-between mt-5">
                <h2 class="mb-2 mt-2">Booking Management</h2>
                <div class="d-flex align-items-center">
                  <%= link_to "Create a new tour", new_tour_path, class: "btn btn-secondary" %>
                </div>
              </div>
              <hr>
                <div class="mb-2 mt-2">
                  <h4>These tours require your attention</h4>
                </div>
              <div class="row d-flex flex-wrap justify-content-start">
                <%= render "guide_booked_tours" %>
              </div>
            </div>
          </div>
          <div class="col-12">
            <div>
              <div class="mb-2 mt-2">
                <h4>Your past tours</h4>
              </div>
              <div class="row d-flex flex-wrap justify-content-start">
                <%= render "guide_past_tours" %>
              </div>
            </div>
          </div>
        </div>
        <% end %>
        <%# END OF BOOKING MANAGEMENT %>
      <% end %>
    </div>
  </div>
</div>
</div>
</div>
</div>