config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "tours#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"

  # Defines the routes for the posts resource
  resources :tours, only: [:index, :show, :new, :create] do
    resources :bookings, only: [:new, :create, :show] do
      resources :reviews, only: [:new, :create]
        member do
          patch :accept
          patch :reject
          patch :cancel
          patch :complete
          patch :no_show
          patch :refund
        end
    end
  end

  # not needed?
  get "users/:id" => "users#show", as: :user

  resources :users, only: [:show] do
    resources :reviews, only: [:index, :destroy]
  end

  get "bookings/:id/edit" => "bookings#edit", as: :booking_edit
  patch "bookings/:id" => "bookings#update", as: :booking
  delete "bookings/:id" => "bookings#destroy", as: :booking_destroy


end

app/models/tour.rb
class Tour < ApplicationRecord
  # geocoded_by :location
  # after_validation :geocode, if: :will_save_change_to_location?

  CATEGORIES = ["Walking Tour", "Van Tour", "Bus Tour", "Free Tour", "Boat Tour"]
  has_many :bookings, dependent: :destroy
  has_many :users, through: :bookings
  has_many :reviews, through: :bookings
  belongs_to :user
  has_one_attached :photo
  validates :name, presence: true
  validates :location, presence: true
  validates :description, presence: true
  validates :duration_in_hours, presence: true, numericality: { only_integer: true }
  validates :price, presence: true, numericality: { only_integer: true }
  # validates :starting_time, presence: true
  validates :category, inclusion: { in: CATEGORIES, message: "%<value>s is not a valid type" }

  include PgSearch::Model
  pg_search_scope :search_by_name_and_location_and_sights_description_and_category,
                  against: %i[name location sights description category],
                  associated_against: {
                    user: %i[first_name last_name language]
                  },
                  using: {
                    tsearch: { prefix: true }
                  }

  def update_tour_avg_rating
    ratings = reviews.pluck(:tour_rating).reject(&:nil?)

    new_rating = ratings.empty? ? nil : (ratings.sum.to_f / ratings.size)

    update(tour_average_rating: new_rating)
  end
end

app/controllers/tours_controller.rb
class ToursController < ApplicationController
  def index
    @tours = Tour.all
    # the 'geocoded' scope filters only tours with coordinates (latitude and longitude)
    @user = current_user
    @users = User.all

    return unless params[:search].present?

    # @tours = @tours.where("name LIKE ?", "%#{params[:search]}%")
    @tours = Tour.search_by_name_and_location_and_sights_description_and_category(params[:search])
  end

  def show
    @tour = Tour.find(params[:id])
    @user = current_user
    @booking = Booking.new(date: Date.today)
    @booking.user = current_user

    @bookings_reviewed = Booking.where(tour_id: @tour.id)
    @reviews_tour = Review.where(booking_id: @bookings_reviewed.pluck(:id))

    @markers = []

    # Add starting point marker
    @markers << { lat: @tour.latitude, lng: @tour.longitude, label: 'Start' }

    # Add ending point marker
    ending_point_coords = Geocoder.coordinates(@tour.ending_point)
    @markers << { lat: ending_point_coords[0], lng: ending_point_coords[1], label: 'End' } if ending_point_coords

    # Add sightseeing spots markers
    return unless @tour.sights.present?

    @tour.sights.split('; ').each do |sight|
      sight_coords = Geocoder.coordinates(sight)
      @markers << { lat: sight_coords[0], lng: sight_coords[1], label: sight } if sight_coords
    end
  end

  def new
    @tour = Tour.new
  end

  def create
    @tour = Tour.new(tour_params)
    @tour.user = current_user
    if @tour.save
      redirect_to tour_path(@tour)
    else
      render :new, unprocessable_entity
    end
  end

  private

  def tour_params
    params.require(:tour).permit(:name, :location, :description, :duration_in_hours, :price, :category, :photo,
                                 :starting_point, :ending_point, :sights)
  end
end

app/views/tours/_banner.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4), rgba(0,0,0,0.4)), url(<%= asset_path('tour_guide.jpg') %>);">
  <div class="container">
    <h1>Explore the world with your perfect guide!</h1>
    <p>Change your life and get the most insightful experience with a local person.</p>
    <%= link_to "#all-tours", class: "btn btn-secondary btn-lg" do %>
    See all tours
    <i class="fa-solid fa-arrow-down fs-6"></i>
    <i class="fa-solid fa-arrow-down fs-6"></i>
    <% end %>
  </div>
</div>

<h2 id="all-tours"></h2> <%# Do not delete, this is a path to see all button %>

app/views/tours/_new.html.erb
<div class="form-container">
  <h2>Create your tour!</h2>

  <%= simple_form_for (@tour) do |f| %>
    <%= f.error_notification %>

    <div class="form-inputs">
      <%= f.input :name,
                  required: true,
                  input_html: { autocomplete: "name" } %>
      <%= f.input :location,
                  required: true,
                  input_html: { autocomplete: "location" } %>
      <%= f.input :description,
                  required: true,
                  autofocus: true,
                  input_html: { autocomplete: "description" }%>
      <%= f.input :duration_in_hours,
                  required: true,
                  input_html: { autocomplete: "duration_in_hours" } %>
      <%= f.input :starting_point,
                  input_html: { autocomplete: "start" } %>
      <%= f.input :ending_point,
                  input_html: { autocomplete: "end" } %>
      <%= f.input :sights,
                  input_html: { autocomplete: "sites" } %>
      <%= f.input :price, checked_value: :true, unchecked_value: :false,
                  required: true,
                  input_html: { autocomplete: "price" } %>
      <%= f.input :category, collection: Tour::CATEGORIES,
                  required: true,
                  input_html: { autocomplete: "category" } %>
      <%= f.input :starting_time,
                  required: true,
                  input_html: { autocomplete: "starting_time" } %>
      <%= f.input :photo, as: :file %>
    </div>

    <div class="form-actions">
      <%= f.button :submit, "Create", class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/tours/index.html.erb
<div data-controller="remove">


  <%# <h2 id="search-bar-header" style="color: #1B435D;">FIND YOUR NEXT TOUR</h2> %>
  <%# <div class="col-12 col-lg-2"> %>
    <%# <div class="search-filter-items"> %>
      <%#= form_with(url: root_path, method: :get, local: true) do %>
        <%# <div class="d-flex"> %>
          <%#= text_field_tag :search, params[:search], class: "form-control", placeholder: "Find a tour" %>
          <%# <button data-action="click->remove#fire" class="btn btn-warning">Search</button> %>
        <%# </div> %>
      <%# end %>
    <%# </div> %>
  <%# </div> %>
  <% unless params[:search].present? %>
    <div data-remove-target="removableElement">
      <%= render "banner" %>
    </div>
  <% end %>
  </div>



<div class="container">

  <div class="row mt-5">
    <% @tours.each do |tour| %>
      <div class="col-4">
        <div class="card-trip m-3">
          <%#= cl_image_tag(tour.photo.key) %>


            <%= link_to tour_path(tour) do %>
              <%= image_tag(tour.photo) %>
            <% end %>

          <div class="card-trip-infos">
            <div class="card-trip-description">
              <div>
                <p><%= link_to tour.name, tour_path(tour), class:"card-link" %></p>
                <p><%= tour.description %></p>
              </div>
              <h2 class="card-trip-pricing"><%= tour.price %>€</h2>
            </div>
            <%#= cl_image_tag(tour.user.photo.key, class: "card-trip-user avatar-bordered") %>
            <%#= tour.user.first_name %>
            <%#= link_to "Your guide", user_path(tour.user) %>
            <%= link_to user_path(tour.user) do %>
              <%= image_tag(tour.user.photo, class: "card-trip-user avatar-bordered") %>
            <% end %>
            <%# <img src="https://kitt.lewagon.com/placeholder/users/krokrob" class="card-trip-user avatar-bordered" /> %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/tours/new.html.erb
<%= render "new", resource: @tour %>

app/views/tours/show.html.erb
<div class="container position-relative">

  <h1 class="mt-3 mb-5 text-center"><%= @tour.name %></h1>

  <!-- Row for Image & Booking Form -->
  <div class="row d-flex align-items-stretch">

    <!-- Tour Image -->
    <div class="col-sm-12 col-md-6 d-flex align-items-center">
      <div class="tour-img">
        <%= cl_image_tag(@tour.photo.key) %>
      </div>
    </div>

    <!-- Booking Form / Sign-Up -->
    <div class="col-sm-12 col-md-6 d-flex align-items-center">
      <div id="form-booking" class="form-container w-100 h-100 d-flex flex-column justify-content-center">
        <% if user_signed_in? %>
          <h2 class="py-3 text-center">Book This Tour</h2>
          <div class="d-flex justify-content-center">
            <%= simple_form_for [@tour, @booking], url: tour_bookings_path(@tour) do |f| %>
              <%= f.input :date, as: :string, input_html: { data: { controller: "datepicker" } } %>
              <%= f.input :pax, input_html: { type: 'number', step: 1 }, label: "Number of participants" %>
              <div class="text-center">
                <%= f.submit "Book", class: "btn btn-action mt-2 btn-lg"%>
              </div>
            <% end %>
          </div>
        <% else %>
          <h5 class="pt-5 pb-2 text-center">Login to book a tour</h5>
          <div class="d-flex align-items-center justify-content-center">
            <%= link_to "Login", new_user_session_path, class: "btn btn-action btn-lg my-2" %>
          </div>
        <% end %>
      </div>
    </div>

    <div class="tour-description col-sm-12 col-md-6 my-5 px-4">
        <h2 class="pb-2">Tour Description</h2>

        <p><%= @tour.description %></p>

        <p><strong>Sights included: </strong>
          <ul>
            <% @tour.sights.split(';').each do |sight| %>
              <li>
                <%= sight.strip.split(",").first.strip %>
              </li>
            <% end %>
          </ul>
        </p>

        <p><strong>Category: </strong><%= @tour.category %></p>
        <p><strong>Length: </strong><%= @tour.duration_in_hours %> hours</p>
        <%# <p><strong>Starting time: </strong><%= @tour.starting_time %>
        <p><strong>Starting point: </strong><%= @tour.starting_point.split(",").first.strip %></p>
        <p><strong>Ending point: </strong><%= @tour.ending_point.split(",").first.strip %></p>

        <%# <%= render 'shared/map_modal'%>

        <p style="margin-top: 1rem;"><strong>Price: </strong><%= @tour.price %> €/person</p>
        <p class="text-popup"><strong>Tour Guide: </strong><%= link_to "#{@tour.user.first_name} #{@tour.user.last_name}", user_path(@tour.user) %></p>
      </div>

    <div class="col-sm-12 col-md-6 my-5 px-4">
      <h3>Reviews

      <% if @reviews_tour.present? %>
        <% if @tour.tour_average_rating.present? %>
          (<%= @tour.tour_average_rating %>)
        <% end %>
        </h3>
        <% @reviews_tour.each do |review| %>
          <hr>
          <div class="row">
            <div class="d-flex col-sm-2 col-lg-2 py-2 pe-0"><p class="fw-bolder"><%= review.booking.user.first_name %>:</p></div>
            <div class="d-flex col-sm-10 col-lg-9 py-2 px-0">
              <%= render "shared/review_content", review: review %>
            </div>
          </div>

          <%= render "shared/review_stars", review: review %>
        <% end %>

      <% else %>
        </h3>
        <p class="fw-light">There are no reviews for this tour yet.</p>
      <% end %>

    </div>
  </div>
</div>