config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "tours#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"

  # Defines the routes for the posts resource
  resources :tours, only: [:index, :show, :new, :create] do
    resources :bookings, only: [:new, :create, :show] do
      resources :reviews, only: [:new, :create]
        member do
          patch :accept
          patch :reject
          patch :cancel
          patch :complete
          patch :no_show
          patch :refund
        end
    end
  end

  # not needed?
  get "users/:id" => "users#show", as: :user

  resources :users, only: [:show] do
    resources :reviews, only: [:index, :destroy]
  end

  get "bookings/:id/edit" => "bookings#edit", as: :booking_edit
  patch "bookings/:id" => "bookings#update", as: :booking
  delete "bookings/:id" => "bookings#destroy", as: :booking_destroy


end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
    @reviews = Review.all
    @user = current_user
    @bookings_reviewed = Booking.where(user_id: @user.id)
    @reviews_user = Review.where(booking_id: @bookings_reviewed.pluck(:id))

    # @reviews_guide = Review.joins(booking: :tour).where(tours: { user_id: @user.id })
  end

  def new
    @booking = Booking.find(params[:booking_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @booking = Booking.find(params[:booking_id])
    @review.booking = @booking
    @review.booking.user = current_user
    if @review.save
      @review.booking.tour.update_tour_avg_rating
      redirect_to user_path(current_user)
      flash[:notice] = "Review was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to user_reviews_path(current_user), notice: "Review was successfully deleted."
  end

  private

  def review_params
    params.require(:review).permit(:review_content, :tour_rating, :guide_rating)
  end
end

app/views/reviews/index.html.erb
<div class="container">

  <%= link_to "< Back to Profile", user_path(@user), class: "btn btn-primary my-3" %>

  <h1 class="my-4">My Reviews</h1>

  <% if @reviews_user.present? %>
    <% @reviews_user.each do |review| %>
      <%# <strong><%= review.booking.tour.name %>
      <h3 class="my-3"><%= review.booking.tour.name %></h3>

      <%= render "shared/review_content", review: review %>
      <%= render "shared/review_stars", review: review %>

      <%= link_to "Delete Review", user_review_path(@user, review), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "btn btn-delete" %>
      <hr>
        <%# <%= button_to "Destroy this restaurant", @restaurant, method: :delete %>
    <% end %>

  <% else %>
    <p class="fw-lighter fst-italic">You have no reviews yet. Write one for one of your previous tours here: </p>
    <%= link_to "Write Review", "#{user_path(@user)}#to-review", class: "btn btn-secondary my-3" %>
  <% end %>
<%# <p><%= @reviews_user.count() %>


</div>

app/views/reviews/new.html.erb
<div id="form-review" class="form-container">
  <%= simple_form_for [@booking, @tour, @review], url: tour_booking_reviews_path(@booking) do |f| %>
  <h3 class="mb-4 text-start">How was your experience on <%=  @booking.tour.name %>?</h3>
    <%= f.input :review_content, label: false, :input_html => {:rows => 5} %>

      <div class="my-4">
        <h4>Tour Rating</h4>
        <div class="star-rating">
            <% (1..5).reverse_each do |i| %>
              <%= f.radio_button :tour_rating, i, id: "tour_star_#{i}" %>
              <label for="tour_star_<%= i %>"></label>
            <% end %>
        </div>
        <div class="mt-3">
          <span id="tour-rating-value" class="h4">0</span> out of 5 stars
        </div>
      </div>

      <div class="my-4">
        <h4>Guide Rating</h4>
        <div class="star-rating ">
          <% (1..5).reverse_each do |i| %>
            <%= f.radio_button :guide_rating, i, id: "guide_star_#{i}" %>
            <label for="guide_star_<%= i %>"></label>
          <% end %>
        </div>
        <div class="mt-3">
          <span id="guide-rating-value" class="h4">0</span> out of 5 stars
        </div>
      </div>

    <%= f.submit "Leave a Review", class: "btn btn-secondary my-3" %>
  <% end %>
</div>

<script>
  const tourStarRating = document.querySelectorAll('input[name="review[tour_rating]"]');
  const tourRatingValue = document.getElementById('tour-rating-value');

  tourStarRating.forEach(star => {
    star.addEventListener('change', function(e) {
      tourRatingValue.textContent = e.target.value;
    });
  });

  const guideStarRating = document.querySelectorAll('input[name="review[guide_rating]"]');
  const guideRatingValue = document.getElementById('guide-rating-value');

  guideStarRating.forEach(star => {
    star.addEventListener('change', function(e) {
      guideRatingValue.textContent = e.target.value;
    });
  });
</script>